from pydantic import BaseModel, Field
from typing import Optional, List, Union
from uuid import UUID
from .attribute_suggestion import AttributeSuggestion
from .relationship_suggestion import RelationshipSuggestion
from .conceptual_model import ConceptualModel

class StartPropertySuggestionsTopKExtractionJobRequest(BaseModel):
    """Represents a request to start a job for extracting top-K property suggestions (i.e. mix of attributes and relationships) from the given set of paragraphs (structural elements) of a legal act for the given class."""
    k: int = Field(default=10, description="Maximal number of top property suggestions to extract in this job (default: 10)")
    selected_class_id: str = Field(description="The ID of the class for which property suggestions are to be generated. This includes attributes owned by the class and relationships mediating the class with another class. If the other class does not exist in the known conceptual model, it will extracted as a new class suggestion but only with name, its definition and explanation will not be generated.")
    structural_element_ids: Optional[List[str]] = Field(default=None, description="The IDs of the structural elements (paragraphs) from which to extract property suggestions. If not provided, the whole legal text will be considered. However, take into account that in that case, the limits given by the LLM API provider, e.g. context window size or transactions-per-minute, can be exceeded resulting in the job failure.")
    context_text: Optional[str] = Field(default=None, description="Additional context text specified by the user to focus suggestion extraction. Be careful in using this as it is not guaranteed to be used in the extraction process. Also take into account that it can break the extraction process if specified maliciously. The job can also be rejected completely if the context is found harmful.")
    known_conceptual_model: Optional[ConceptualModel] = Field(default=None, description="Existing conceptual model to consider during the extraction job. The extraction job will try to generate new suggestions that are semantically close to the existing model and it will try to avoid generating suggestions that are already present in the existing model. If not provided, the job will generate suggestions without considering any existing model.")

class StartPropertySuggestionsJobResponse(BaseModel):
    """Represents a response to a request for starting a property (attribute, relationship) suggestions extraction job."""
    job_id: UUID = Field(description="Unique identifier for the started job")
    selected_class_id: str = Field(description="The ID of the class for which property suggestions are to be generated")
    status: Optional[str] = Field(default=None, description="Current status of the job ('in_progress', 'completed', 'failed')")

class PropertySuggestionsJobStatusResponse(BaseModel):
    job_id: UUID = Field(description="Unique identifier of the job")
    selected_class_id: str = Field(description="The ID of the class for which property suggestions are being generated")
    status: str = Field(description="Current status of the job ('in_progress', 'completed', 'failed')")
    new_attribute_suggestions: List[AttributeSuggestion] = Field(default=[], description="List of extracted attribute suggestions since the start of the job. After 'completed' status is set, this list contains all suggestions generated by the job. No more suggestions will be added after the job is completed.")
    new_relationship_suggestions: List[RelationshipSuggestion] = Field(default=[], description="List of extracted relationship suggestions since the start of the job. After 'completed' status is set, this list contains all suggestions generated by the job. No more suggestions will be added after the job is completed.")
