CREATE TABLE IF NOT EXISTS suggestion_jobs (
    job_id UUID PRIMARY KEY,
    job_kind TEXT NOT NULL CHECK (job_kind IN ('CLASS', 'PROPERTY', 'RELATIONSHIP', 'VOCABULARY')),
    selected_class_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')),
    suggestions JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS feedback_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL,
    suggestion_id TEXT NOT NULL,
    feedback_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_feedback_job
        FOREIGN KEY (job_id)
        REFERENCES suggestion_jobs(job_id)
);

CREATE INDEX IF NOT EXISTS idx_suggestion_jobs_status ON suggestion_jobs(status);
CREATE INDEX IF NOT EXISTS idx_feedback_records_job_id ON feedback_records(job_id);

CREATE TABLE IF NOT EXISTS token_usage (
    user_id TEXT NOT NULL,
    usage_date DATE NOT NULL,
    tokens_spent INTEGER NOT NULL DEFAULT 0 CHECK (tokens_spent >= 0),
    PRIMARY KEY (user_id, usage_date)
);

CREATE TABLE IF NOT EXISTS legal_acts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number SMALLINT NOT NULL CHECK (number >= 0),
    year SMALLINT NOT NULL CHECK (year >= 0),
    date DATE NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS legal_act_texts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_act_id BIGINT NOT NULL,
    path TEXT NOT NULL,
    legal_text TEXT NOT NULL,
    legal_hierarchy TEXT NOT NULL,
    legal_order TEXT NOT NULL,

    CONSTRAINT fk_acts
        FOREIGN KEY (legal_act_id)
        REFERENCES legal_acts(id)
);

CREATE INDEX IF NOT EXISTS idx_legal_acts_number_year_date ON legal_acts(number, year, date);
CREATE INDEX IF NOT EXISTS idx_legal_act_texts_legal_act_id ON legal_act_texts(legal_act_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_legal_act_texts_path ON legal_act_texts(path text_pattern_ops);

-- Upgrade databases created before the aggregated vocabulary job was introduced.
ALTER TABLE suggestion_jobs DROP CONSTRAINT IF EXISTS suggestion_jobs_job_kind_check;
ALTER TABLE suggestion_jobs ADD CONSTRAINT suggestion_jobs_job_kind_check
    CHECK (job_kind IN ('CLASS', 'PROPERTY', 'RELATIONSHIP', 'VOCABULARY'));
