CREATE TABLE IF NOT EXISTS feedback_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL,
    suggestion_id TEXT NOT NULL,
    feedback_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS legal_acts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number SMALLINT NOT NULL CHECK (number >= 0),
    year SMALLINT NOT NULL CHECK (year >= 0),
    date DATE NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS legal_act_texts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_act_id BIGINT NOT NULL,
    legal_text TEXT NOT NULL,
    official_id TEXT NOT NULL,
    official_number TEXT NOT NULL,
    successor BIGINT,

    CONSTRAINT fk_acts
        FOREIGN KEY (legal_act_id)
        REFERENCES legal_acts(id),

    CONSTRAINT fk_successor
        FOREIGN KEY (successor)
        REFERENCES legal_act_texts(id)
);

CREATE INDEX IF NOT EXISTS idx_feedback_records_job_id ON feedback_records(job_id);
CREATE INDEX IF NOT EXISTS idx_feedback_records_suggestion_id ON feedback_records(suggestion_id);
CREATE INDEX IF NOT EXISTS idx_legal_act_texts_legal_act_id ON legal_act_texts(legal_act_id);
